nodes:
  n1:
    id: "n1"
    address: "localhost:5001"
  n2:
    id: "n2"
    address: "localhost:5002"
  n3:
    id: "n3"
    address: "localhost:5003"
  n4:
    id: "n4"
    address: "localhost:5004"
  n5:
    id: "n5"
    address: "localhost:5005"
  n6:
    id: "n6"
    address: "localhost:5006"
  n7:
    id: "n7"
    address: "localhost:5007"

clients:
  A:
    id: "A"
    address: "localhost:6001"
  B:
    id: "B"
    address: "localhost:6002"
  C:
    id: "C"
    address: "localhost:6003"
  D:
    id: "D"
    address: "localhost:6004"
  E:
    id: "E"
    address: "localhost:6005"
  F:
    id: "F"
    address: "localhost:6006"
  G:
    id: "G"
    address: "localhost:6007"
  H:
    id: "H"
    address: "localhost:6008"
  I:
    id: "I"
    address: "localhost:6009"
  J:
    id: "J"
    address: "localhost:6010"

db_dir: ./data
init_balance: 69
